### ISSUE TITLE
Check that none of the inputs are NaNs

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#1105]
Sometimes NEA is silly and returns a NaN for a system parameter. EXOTIC needs to check and allow the user to override if a NaN is detected for that parameter *and its associated uncertainty*

**Comment by rzellem** [comment]
This is also an issue for WASP-140b (or any other target where NEA returns a NaN for a parameter):

```
Looking up WASP-140 b on the NASA Exoplanet Archive. Please wait....
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "exotic/exotic_gui.py", line 1252, in save_input
    input_data['pName'], CandidatePlanetBool, pDict = nea_obj.planet_info()
  File "/Users/rzellem/Documents/EXOTIC/exotic/api/nea.py", line 120, in planet_info
    self._get_params(data[idx])
  File "/Users/rzellem/Documents/EXOTIC/exotic/api/nea.py", line 310, in _get_params
    if data['pl_ratdor'] < 1 or np.isnan(data['pl_ratdor']):
TypeError: '<' not supported between instances of 'NoneType' and 'int'

```

Need to handle exceptions like this a little bit more robustly.
