### ISSUE TITLE
installing with python 3.11

### ISSUE THREAD

**Issue by kennethcarrell** [rzellem/EXOTIC#1160]
Hello, I am trying to install this to run on python 3.11 and the numba package will not install because it requires >=3.7 and <3.11:
```
Collecting numba
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/f3/f72npmmd6fvggqk5kyq97f3jrdrw_p/T/pip-install-ssybi0bg/numba_78c60ea57f4c4a4fb9bc3d4a66b446cf/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/private/var/folders/f3/f72npmmd6fvggqk5kyq97f3jrdrw_p/T/pip-install-ssybi0bg/numba_78c60ea57f4c4a4fb9bc3d4a66b446cf/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.2; only versions >=3.7,<3.11 are supported.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
INFO: Launching EXOTIC user interface. ...
ERROR: Unable to launch EXOTIC, installation failed. Please verify installation
       steps reported on screen or open a support ticket at: 
       https://github.com/rzellem/EXOTIC/issues/new/choose .
       EXITING!

```

**Comment by kennethcarrell** [comment]
An update.

This error was because of an issue with numba not being supported on 3.11.x

So, I went back to python 3.8.10 (version 3.9 do not work with Tk on macOS)

Then, I had the following error:

```
Traceback (most recent call last):
 File "exotic.py", line 110, in <module>
  from .api.ld import LimbDarkening
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "exotic.py", line 112, in <module>
  from api.ld import LimbDarkening
 File "/Users/kcarrell/Desktop/EXOTIC-2.8.0/exotic/api/ld.py", line 4, in <module>
  from .gael_ld import createldgrid
 File "/Users/kcarrell/Desktop/EXOTIC-2.8.0/exotic/api/gael_ld.py", line 43, in <module>
  import ldtk
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ldtk/__init__.py", line 21, in <module>
  from .ldtk import LDPSetCreator, LDPSet, load_ldpset
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ldtk/ldtk.py", line 26, in <module>
  from numba import njit
 File "/Users/kcarrell/Library/Python/3.8/lib/python/site-packages/numba/__init__.py", line 43, in <module>
  from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
 File "/Users/kcarrell/Library/Python/3.8/lib/python/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
  from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
 File "/Users/kcarrell/Library/Python/3.8/lib/python/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
  from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
/usr/local/bin/python3: can't open file 'exotic/exotic.py': [Errno 2] No such file or directory
```

I quick Google search gave [this webpage](https://github.com/numba/numba/issues/8615) with a similar problem - basically, numba and numpy were not playing nice.

So, I uninstalled both the numba and numpy packages.  Then I installed numba, which automatically installed the correct version of numpy.

Now, everything seems to be working.
