### ISSUE TITLE
Upgrade to Cython 3

### ISSUE THREAD

**Issue by jpl-jengelke** [rzellem/EXOTIC#1202]
[Changes are fairly extensive in the Cython 3.x upgrade (version 0.x to 3.x)](https://cython.readthedocs.io/en/latest/src/changes.html) so any detailed testing would be beneficial to validate with the updated library.

This should be done for obvious reasons but also because Cython 3 improves compatibility with newer Python versions. 

Currently some of EXOTIC's dependencies are relying on Cython 3, so it would be beneficial to unify the dependency tree by upgrading EXOTIC to avoid any unforeseen, weird interactions between old and new libraries.  The place to update Cython is `pyproject.toml` and the change (sans testing) is in this ticket's eponymously named branch.

**Comment by jpl-jengelke** [comment]
We see these errors in develop while running `python3 exotic/exotic.py -red inits.json -nea`: 
```
Current comparison star is variable, proceeding to next star.
Added Comparison Star #2 [183,166] from AAVSO
Added Comparison Star #3 [324,365] from AAVSO
Finding transformation 1 of 142 : /Users/rzellem/Documents/EXOTIC/sample-data/HatP32Dec202017/HATP-32171220013343.FITS
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/exotic", line 8, in <module>
    sys.exit(main())
  File "/Users/rzellem/Documents/EXOTIC/exotic/exotic.py", line 2124, in main
    aper_data["target"][i][a][an], aper_data["target_bg"][i][a][an] = aperPhot(imageData, 0,
  File "/Users/rzellem/Documents/EXOTIC/exotic/exotic.py", line 1137, in aperPhot
    bgflux, sigmabg, Nbg = skybg_phot(data, starIndex, xc, yc, r + 2, dr)
  File "/Users/rzellem/Documents/EXOTIC/exotic/exotic.py", line 1204, in skybg_phot
    return mode(dat.flatten(), nan_policy='omit').mode[0], np.nanstd(dat.flatten()), np.sum(mask)
IndexError: invalid index to scalar variable.
rzellem@MT-306068 EXOTIC % 
```

The `pip3` freeze shows the following: 
```
asteval==0.9.31
astroalign==2.4.2
astropy==5.3.1
astroquery==0.4.6
barycorrpy==0.4.4
beautifulsoup4==4.12.2
bleach==6.0.0
bokeh==2.4.3
build==0.10.0
certifi==2023.7.22
charset-normalizer==3.2.0
colorcet==3.0.1
colour-demosaicing==0.2.3
colour-science==0.4.2
contourpy==1.1.0
corner==2.2.2
cycler==0.11.0
Cython==3.0.0
emcee==3.1.4
exceptiongroup==1.1.2
execnet==2.0.2
-e git+ssh://git@github.com/rzellem/EXOTIC.git@5059fc168fb8a7a34c23663928f31792eb975a45#egg=exotic
fonttools==4.41.1
future==0.18.3
holoviews==1.16.2
html5lib==1.1
idna==3.4
imageio==2.31.1
importlib-metadata==6.8.0
imreg-dft==2.0.0
iniconfig==2.0.0
jaraco.classes==3.3.0
Jinja2==3.1.2
jplephem==2.18
keyring==24.2.0
kiwisolver==1.4.4
lazy_loader==0.3
LDTk==1.8.3
llvmlite==0.40.1
lmfit==1.2.2
Markdown==3.4.3
MarkupSafe==2.1.3
matplotlib==3.7.2
more-itertools==10.0.0
networkx==3.1
numba==0.57.1
numpy==1.24.4
packaging==23.1
pandas==1.5.3
panel==0.13.1
param==1.13.0
photutils==1.8.0
Pillow==10.0.0
pluggy==1.2.0
pyct==0.5.0
pyerfa==2.0.0.3
pylightcurve==4.0.1
pyparsing==3.0.9
pyproject_hooks==1.0.0
pytest==7.4.0
pytest-xdist==3.3.1
python-dateutil==2.8.2
python-version==0.0.2
pytz==2023.3
pyviz-comms==2.3.2
pyvo==1.4.1
PyWavelets==1.4.1
PyYAML==6.0.1
requests==2.31.0
scikit-image==0.21.0
scipy==1.11.1
semantic-version==2.10.0
sep==1.2.1
six==1.16.0
soupsieve==2.4.1
tenacity==8.2.2
tifffile==2023.7.18
tomli==2.0.1
tornado==6.3.2
tqdm==4.65.0
traitlets==5.9.0
typing_extensions==4.7.1
ultranest==3.6.2
uncertainties==3.1.7
urllib3==2.0.4
webencodings==0.5.1
zipp==3.16.2
```
