### ISSUE TITLE
SciPy `mode` returning different data type breaking reduction transformations

### ISSUE THREAD

**Issue by jpl-jengelke** [rzellem/EXOTIC#1206]
In some cases, in newer Python versions, SciPy mode returns a float when an array is expected. This breaks generation of reduction transformations. (This is happening with SciPy 1.11.1.)

```
Added Comparison Star #3 [324,365] from AAVSO
Finding transformation 1 of 142 : /proj/survey-ws/source/EXOTIC_sampledata/HatP32Dec202017/HATP-32171220013343.FITS
Traceback (most recent call last):
  File "/System/Volumes/Data/proj/survey-ws/source/EXOTIC/exotic/exotic.py", line 2641, in <module>
    main()
  File "/System/Volumes/Data/proj/survey-ws/source/EXOTIC/exotic/exotic.py", line 2124, in main
    aper_data["target"][i][a][an], aper_data["target_bg"][i][a][an] = aperPhot(imageData, 0,
                                                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/System/Volumes/Data/proj/survey-ws/source/EXOTIC/exotic/exotic.py", line 1137, in aperPhot
    bgflux, sigmabg, Nbg = skybg_phot(data, starIndex, xc, yc, r + 2, dr)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/System/Volumes/Data/proj/survey-ws/source/EXOTIC/exotic/exotic.py", line 1204, in skybg_phot
    return mode(dat.flatten(), nan_policy='omit').mode[0], np.nanstd(dat.flatten()), np.sum(mask)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: invalid index to scalar variable.
```

**Comment by jpl-jengelke** [comment]
https://github.com/scipy/scipy/issues/18957
