### ISSUE TITLE
Need help fixing an error during install

### ISSUE THREAD

**Issue by edove07** [rzellem/EXOTIC#1246]
Hello,
Can anyone point me in the write direction to fix this error?
pip 24.0 from C:\Python\3.12.1150.0\Lib\site-packages\pip (python 3.12)
DEPRECATION: Loading egg at c:\python\3.12.1150.0\lib\site-packages\mulensmodel-2.20.0-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
'#' is not recognized as an internal or external command,
operable program or batch file.
DEPRECATION: Loading egg at c:\python\3.12.1150.0\lib\site-packages\mulensmodel-2.20.0-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Collecting exotic
  Using cached exotic-3.3.0-py3-none-any.whl.metadata (15 kB)
Collecting astroalign~=2.4 (from exotic)
  Using cached astroalign-2.5.1-py3-none-any.whl.metadata (6.7 kB)
Collecting astropy~=5.3.1 (from exotic)
  Using cached astropy-5.3.4-cp312-cp312-win_amd64.whl.metadata (9.6 kB)
Collecting astroquery~=0.4 (from exotic)
  Using cached astroquery-0.4.7-py3-none-any.whl.metadata (7.2 kB)
Collecting barycorrpy~=0.4 (from exotic)
  Using cached barycorrpy-0.4.4-py3-none-any.whl.metadata (4.1 kB)
Collecting colour-demosaicing~=0.2.3 (from exotic)
  Using cached colour_demosaicing-0.2.5-py3-none-any.whl.metadata (6.4 kB)
Collecting holoviews~=1.16 (from exotic)
  Using cached holoviews-1.18.3-py2.py3-none-any.whl.metadata (21 kB)
Collecting imreg-dft~=2.0 (from exotic)
  Using cached imreg_dft-2.0.0.tar.gz (101 kB)
  Preparing metadata (setup.py) ... done
Collecting LDTk~=1.8 (from exotic)
  Using cached ldtk-1.8.4-py3-none-any.whl.metadata (992 bytes)
Collecting lmfit~=1.2 (from exotic)
  Using cached lmfit-1.2.2-py3-none-any.whl.metadata (9.9 kB)
Collecting matplotlib~=3.7.2 (from exotic)
  Using cached matplotlib-3.7.5-cp312-cp312-win_amd64.whl.metadata (5.8 kB)
Collecting numpy~=1.24.4 (from exotic)
  Using cached numpy-1.24.4.tar.gz (10.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  **× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Python\3.12.1150.0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Python\3.12.1150.0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python\3.12.1150.0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Python\3.12.1150.0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python\3.12.1150.0\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\thund\AppData\Local\Temp\pip-build-env-vinntv_u\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\thund\AppData\Local\Temp\pip-build-env-vinntv_u\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\thund\AppData\Local\Temp\pip-build-env-vinntv_u\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.**

note: This error originates from a subprocess, and is likely not a problem with pip.
Press any key to continue . . .

**Comment by rzellem** [comment]
Hi @edove07 ! Did you check out our installation instructions for Windows computers on our website? Usually the installation is the issue and hopefully this will resolve your problem! if not- let me know!

https://exoplanets.nasa.gov/exoplanet-watch/how-to-contribute/how-to-analyze-your-data/exotic-downloadable/

**Comment by edove07** [comment]
@rzellem Thanks the link you provided helped! The git hub page said to install the latest Python version, and this one specified 3.10, downgrading and running solved the issue. Thanks again!

**Comment by rzellem** [comment]
Awesome! Glad it worked! Yeah, the GUI system interface that we use is *supposed* to be natively supported by Python...but in practice, it is only supported on certain versions. :sigh:

As a heads up, we usually recommend that only our Advanced users install EXOTIC locally - you might want to try out the online Google Colab version instead - it is MUCH more user friendly (and at the very least, it might help you to understand how to run EXOTIC locally!).

Good luck and let us know if you run into any more issues!

**Comment by jpl-jengelke** [comment]
EXOTIC 4.2.0 was just released to address compatibility. Closing this as resolved.
