### ISSUE TITLE
Python 3.12 ModuleNotFoundError: No module named 'importlib_metadata'

### ISSUE THREAD

**Issue by ivenzor** [rzellem/EXOTIC#1331]
Although `importlib_metadata` is listed in the requirements only for Python 3.6 and 3.7, it was still installed in Python 3.10 as a prerequisite for   `keyring` , which is a dependency of  `astroquery`.
However, in Python 3.12  `importlib_metadata` is not installed as a dependency of any other package but `import_metadata` is still used in` exotic/__init__.py`

```
(exotic_env2) C:\Users\ivenz>exotic
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ivenz\miniconda3\envs\exotic_env2\Scripts\exotic.exe\__main__.py", line 5, in <module>
  File "C:\Users\ivenz\miniconda3\envs\exotic_env2\Lib\site-packages\exotic\__init__.py", line 38, in <module>
    import importlib_metadata as metadata
ModuleNotFoundError: No module named 'importlib_metadata'
```

**Comment by ivenzor** [comment]
@jpl-jengelke @tamimfatahi  I guess we could change import importlib_metadata as metadata for the standard library importlib.metadata 
I could work later tonight on this, unless you are already working on this.

**Comment by ivenzor** [comment]
https://github.com/rzellem/EXOTIC/pull/1332
