### ISSUE TITLE
Pylightcurve breaking DB upgrade from 4.0.1 to 4.0.4 causing execution failures

### ISSUE THREAD

**Issue by ivenzor** [rzellem/EXOTIC#1346]
`pylightcurve` was very recently upgraded from` 4.0.1` to `4.0.4`, and the upgrade brings significant changes: https://github.com/ucl-exoplanets/pylightcurve/commit/72bd85783f971b9d60837bb5e7ba3299a19f32be

In particular, it changes how the ExoTETHyS, ephemerides, and photometry databases are cached and used. This can break EXOTIC, even if you’re using virtual environments, if some environments used Pylightcurve 4.0.1 and others are now using 4.0.4. The issue was initially found by Allen and then expanded upon by  @mikeprimm https://uol-ets.slack.com/archives/CJJRP4QKV/p1731417925869009
I'm able to replicate the error in my local installation.

My proposal is as follows: we could pin Pylightcurve to exactly 4.0.1. Currently, we allow pylightcurve~=4.0.1, which will now install 4.0.4 for new installations, causing errors in EXOTIC if an "old" 4.0.1 installation was used previously on that system. This is NOT affecting Colab users as we have a new environment each time. This will likely affect all local users when they upgrade EXOTIC or create a new virtual env with a new EXOTIC installation.

I’m going to submit a PR for your consideration. It would pin the version of pylightcurve to 4.0.1, until we have an easy way to handle the pylightcurve upgrade (Michael mentioned a possible workaround manually flushing the "old" cache) and to review if there are other major changes we need to be aware related to pylightcurve upgrade from 4.0.1 to 4.0.4

@jpl-jengelke @rzellem @tamimfatahi

**Comment by ivenzor** [comment]
PR #1347

**Comment by mikeprimm** [comment]
I was able to get 4.0.4 working, but it seemed to require manual flushing of the locally cached database files.  pylightcurve currently does caching at an unconditional location (that is VERY virtual environment hostile) - basically "<home-dir>/.pylightcurve4" - and I suspect the changes mentioned above were made without dealing with 'cache consistency' (that is, change of format of the databases without invalidating the existing caches), but I'm not 100% sure.  It'd track with being able to get things functioning by zapping the cache directory, though.

**Comment by ivenzor** [comment]
It seems that if you had 4.0.1 on your system and upgraded to 4.0.4, the 'fix' is to manually delete the .pylightcurve4 cache and then let 4.0.4 load the new data.

However, the reverse doesn’t work.  If you’re on 4.0.4 and want to go back to 4.0.1, even after deleting the .pylightcurve4 folder and reinstalling 4.0.1you will still encounter errors. I’ll try some workarounds tomorrow night.

**Comment by jpl-jengelke** [comment]
@ivenzor Did you make a ticket on the [PyLightCurve repo](https://github.com/ucl-exoplanets/pylightcurve/issues)? Please do so and repost back here. I think we are fine pinning the module, but hopefully we can pin it to the most recent version possible.

**Comment by jpl-jengelke** [comment]
On tighter inspection, I think we would want to try `4.0.3` There was a bug with Numpy float issues fixed there. Additionally, I note the probably breaking change is this change from [4.0.4](https://github.com/ucl-exoplanets/pylightcurve/compare/v4.0.3...v4.0.4#diff-1818f1d282ef921149cd68a63799836522bec6677731dd47f497523cd011c18cL19) where the actual database appears updated. @ivenzor: What are your thoughts?

**Comment by ivenzor** [comment]
@jpl-jengelke There are two reasons:
1) Until a few days ago, we were all using 4.0.1, so we know it works.
2) There is no 4.0.3 version on PyPI; it jumps from 4.0.1 to 4.0.4. We could use pip install from the repository for a specific version not available on PyPI if needed.

Mike has a ticket open with Pylightcurve, but I believe it’s unrelated to the upgrade issue and is more about permissions to the Dropbox files. I’ll review the issue and create a new one if necessary.

**Comment by jpl-jengelke** [comment]
It looks like @mikeprimm opened a [ticket against pylightcurve](https://github.com/ucl-exoplanets/pylightcurve/issues/17#issuecomment-2473693349) for this issue.

**Comment by jpl-jengelke** [comment]
@ivenzor wrote:
> I proposed to pin 4.0.1 for two reasons:
> 
> 1. Until a few days ago, we were all using 4.0.1, so we know it works.
> 2. There is no 4.0.3 version on PyPI; it jumps from 4.0.1 to 4.0.4.
Those are solid reasons but we still need to test `4.0.1` with all the other dependency upgrades in the current release, like on a completely clean install. There could still be incompatibilities, unless you know for sure there aren't any. ...

**Comment by jpl-jengelke** [comment]
@ivenzor Unfortunately, the installation with a clean Pylightcurve 4.0.1 is now broken. ... 
```
prompt$ python3 exotic/exotic.py 
Importing Python Packages - please wait.
Matplotlib is building the font cache; this may take a moment.
Status messages could not be retrieved
Downloading https://hpiers.obspm.fr/iers/eop/eopc04/eopc04.1962-now
|===========================================| 5.0M/5.0M (100.00%)         1s
    Downloading __databases__.pickle_new...
    Done!| ... 
    Downloading exotethys.pickle...
    Done!/ ... 
    Downloading exotethys.zip...
    Done!- ... 
Checking exotethys database...
    Downloading ephemerides.pickle...
    Done!/ ... 
    Downloading ephemerides.zip...
    Done!| ... 
Checking ephemerides database...
    Downloading photometry.pickle...
    Done!\ ... 
Checking photometry database...
Traceback (most recent call last):
  File "/<some_path>/source/EXOTIC/exotic/exotic.py", line 108, in <module>
    from .api.elca import lc_fitter, binner, transit, get_phase
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<some_path>/source/EXOTIC/exotic/exotic.py", line 110, in <module>
    from api.elca import lc_fitter, binner, transit, get_phase
  File "/<some_path>/source/EXOTIC/exotic/api/elca.py", line 47, in <module>
    from pylightcurve.models.exoplanet_lc import transit as pytransit
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pylightcurve/__init__.py", line 14, in <module>
    from pylightcurve.catalogues.catalogues import *
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pylightcurve/catalogues/catalogues.py", line 6, in <module>
    from pylightcurve.__databases__ import plc_data
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pylightcurve/__databases__.py", line 301, in <module>
    plc_data = PlcData()
               ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pylightcurve/__databases__.py", line 58, in __init__
    self.photometry_loaded = self._setup_database('photometry')
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pylightcurve/__databases__.py", line 228, in _setup_database
    current_database = open_dict(database_file_path_old)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pylightcurve/processes/files.py", line 23, in open_dict
    return pickle.load(open(path, 'rb'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, '<'.
prompt$ 
```

Unfortunately, I have tried all manner of testing this (including DB delete with `rm -rf ~/.pylightcurve*`) and reloading the `4.0.1` DB now does *not* work at all.

@rzellem @ivenzor Apparently something changed again with their DB files so I don't think we can pin to 4.0.1. I am removing it in favor of providing the above delete command in release notes.

**Comment by jpl-jengelke** [comment]
Continued with solution in #1355 ...
