### ISSUE TITLE
Check for corrupted FITS files

### ISSUE THREAD

**Issue by tamimfatahi** [rzellem/EXOTIC#244]

**Comment by pearsonkyle** [comment]
## Error

```
Traceback (most recent call last):
  File "/home/dave/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/base.py", line 406, in _readfrom_internal
    header_str, header = _BasicHeader.fromfile(data)
  File "/home/dave/.local/lib/python3.8/site-packages/astropy/io/fits/header.py", line 2077, in fromfile
    header_str, cards = parse_header(fileobj)
  File "astropy/io/fits/_utils.pyx", line 36, in astropy.io.fits._utils.parse_header
Exception
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "exotic.py", line 1732, in <module>
    hdul = fits.open(name=fileName, memmap=False, cache=False, lazy_load_hdus=False)  # opens the fits file
  File "/home/dave/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 164, in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, cache,
  File "/home/dave/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 403, in fromfile
    return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
  File "/home/dave/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 1079, in _readfrom
    read_one = hdulist._read_next_hdu()
  File "/home/dave/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 1154, in _read_next_hdu
    hdu = _BaseHDU.readfrom(fileobj, **kwargs)
  File "/home/dave/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/base.py", line 325, in readfrom
    hdu = cls._readfrom_internal(fileobj, checksum=checksum,
  File "/home/dave/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/base.py", line 413, in _readfrom_internal
    header = Header.fromfile(data,
  File "/home/dave/.local/lib/python3.8/site-packages/astropy/io/fits/header.py", line 513, in fromfile
    return cls._from_blocks(block_iter, is_binary, sep, endcard,
  File "/home/dave/.local/lib/python3.8/site-packages/astropy/io/fits/header.py", line 596, in _from_blocks
    raise OSError('Header missing END card.')
OSError: Header missing END card.
```

## Solution
` fits.open(filename, ignore_missing_end=True)`
