### ISSUE TITLE
More robustly filter out targets that get too close to the detector edge

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#297]
```
***************************************************************
Determining Optimal Aperture and Annulus Size for Comp Star #1
***************************************************************
Target X: 539.0 Target Y: 210.0
Comparison X: 598.0 Comparison Y: 286.0
Testing Comparison Star #1 with a 2 pixel aperture and a 5 pixel annulus.
*************************************************************************************
WARNING: In image 0, your target star has drifted too close to the edge of the detector.
All the remaining images after image #-1 will be ignored
Filtering data to account for drifting target.
Traceback (most recent call last):
  File "exotic.py", line 2816, in <module>
    main()
  File "exotic.py", line 2226, in main
    filtered_data = sigma_clip(arrayFinalFlux, sigma=3)
  File "exotic.py", line 163, in sigma_clip
    std = np.nanmedian([np.nanstd(np.random.choice(res,50)) for i in range(100)])
  File "exotic.py", line 163, in <listcomp>
    std = np.nanmedian([np.nanstd(np.random.choice(res,50)) for i in range(100)])
  File "mtrand.pyx", line 900, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
martin@DESKTOP-90ED50J:/mnt/c/Users/daneb/EXOTIC/exotic$
```

https://www.dropbox.com/sh/pyv932dtur4kz7e/AAA3OKUwJp1k_ouP2TLzGFvTa?dl=0

**Comment by tamimfatahi** [comment]
Downloaded the data and EXOTIC is now able to reduce this dataset. Here are the results: 

[FinalLightCurve_HAT-P-3 b_2020-Apr-23.pdf](https://github.com/rzellem/EXOTIC/files/6927594/FinalLightCurve_HAT-P-3.b_2020-Apr-23.pdf)
![Triangle_HAT-P-3 b_2020-Apr-23](https://user-images.githubusercontent.com/32148306/128099839-06d1daab-17df-4d01-8ce3-e29cb1526cd2.png)
[AAVSO_HAT-P-3 b_2020-Apr-23.txt](https://github.com/rzellem/EXOTIC/files/6927595/AAVSO_HAT-P-3.b_2020-Apr-23.txt)

Works now due to the changes since then.
