### ISSUE TITLE
Fill in missing fields from NEA Scrape

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#421]
```https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+pl_name,hostname,tran_flag,pl_massj,pl_radj,pl_radjerr1,pl_ratdor,pl_ratdorerr1,pl_ratdorerr2,pl_orbincl,pl_orbinclerr1,pl_orbinclerr2,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbeccen,pl_orblper,pl_tranmid,pl_tranmiderr1,pl_tranmiderr2,pl_trandep,pl_trandeperr1,pl_trandeperr2,pl_ratror,pl_ratrorerr1,pl_ratrorerr2,st_teff,st_tefferr1,st_tefferr2,st_met,st_meterr1,st_meterr2,st_logg,st_loggerr1,st_loggerr2,st_mass,st_rad,st_raderr1,ra,dec,pl_pubdate+from+ps+where+tran_flag+=+1+and+default_flag+=+1+and+pl_name+=+'Kepler-1520+b'+order+by+pl_pubdate+desc+&format=csv
https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+pl_name,hostname,tran_flag,pl_massj,pl_radj,pl_radjerr1,pl_ratdor,pl_ratdorerr1,pl_ratdorerr2,pl_orbincl,pl_orbinclerr1,pl_orbinclerr2,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbeccen,pl_orblper,pl_tranmid,pl_tranmiderr1,pl_tranmiderr2,pl_trandep,pl_trandeperr1,pl_trandeperr2,pl_ratror,pl_ratrorerr1,pl_ratrorerr2,st_teff,st_tefferr1,st_tefferr2,st_met,st_meterr1,st_meterr2,st_logg,st_loggerr1,st_loggerr2,st_mass,st_rad,st_raderr1,ra,dec,pl_pubdate+from+ps+where+tran_flag=1+and+pl_name+=+'Kepler-1520+b'+order+by+pl_pubdate+desc+&format=csv
Traceback (most recent call last):
  File "exotic/exotic.py", line 2981, in <module>
    main()
  File "exotic/exotic.py", line 1808, in main
    userpDict['pName'], CandidatePlanetBool, pDict = nea_obj.planet_info()
  File "exotic/exotic.py", line 214, in planet_info
    self._get_params(data[idx])
  File "exotic/exotic.py", line 382, in _get_params
    'incUnc': np.sqrt(np.abs(data['pl_orbinclerr1']*data['pl_orbinclerr2'])),
TypeError: unsupported operand type(s) for *: 'NoneType' and 'NoneType'
MT-100553:EXOTIC rzellem$ 
```

**Comment by pearsonkyle** [comment]
Resolved in this pr: https://github.com/rzellem/EXOTIC/pull/422
