### ISSUE TITLE
ValueError: Residuals are not finite in the initial point.

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#481]
Error occurs with this dataset: https://drive.google.com/drive/folders/1iLg1oE9zUwUNueXlZcvh2hP5xb83c93P

```
***************************************************************
Determining Optimal Aperture and Annulus Size for Comp Star #1
***************************************************************

Target X: 422.0 Target Y: 287.0

Comparison X: 465.0 Comparison Y: 182.0

array must not contain infs or NaNs
bounded  light curve fitting failed...check priors (e.g. estimated mid-transit time + orbital period)
bound: [0.0, 0.12614785471818377] prior: 8.381362935113955e-16
bound: [2457901.8076311797, 2457901.8130961796] prior: 2457901.8083046614
bound: [4.853, 6.0329999999999995] prior: 4.882452239064095
bound: [0.4121315125578704, 10040.104476079101] prior: 132.20130583928523
bound: [-1.0, 1.0] prior: -0.9178761929519315
removing bounds and trying again...
Residuals are not finite in the initial point.
bounded  light curve fitting failed...check priors (e.g. estimated mid-transit time + orbital period)
bound: [0.0, 0.12614785471818377] prior: 0.10091828377454702
bound: [2457901.8076311797, 2457901.8130961796] prior: 2457901.8103636797
bound: [4.853, 6.0329999999999995] prior: 5.443
bound: [0.0, 13095.033236587356] prior: 127.92269362456162
bound: [-1.0, 1.0] prior: 0.0
removing bounds and trying again...
Traceback (most recent call last):
  File "/Users/rzellem/Downloads/EXOTIC-0.29.0/exotic/api/elca.py", line 271, in fit_LM
    res = least_squares(lc2min, x0=[self.prior[k] for k in freekeys],
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scipy/optimize/_lsq/least_squares.py", line 814, in least_squares
    raise ValueError("Residuals are not finite in the initial point.")
ValueError: Residuals are not finite in the initial point.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "exotic/exotic.py", line 3320, in <module>
    main()
  File "exotic/exotic.py", line 2752, in main
    myfit = lc_fitter(
  File "/Users/rzellem/Downloads/EXOTIC-0.29.0/exotic/api/elca.py", line 254, in __init__
    self.fit_LM()
  File "/Users/rzellem/Downloads/EXOTIC-0.29.0/exotic/api/elca.py", line 281, in fit_LM
    res = least_squares(lc2min, x0=[self.prior[k] for k in freekeys], method='lm', jac='3-point', loss='linear')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scipy/optimize/_lsq/least_squares.py", line 814, in least_squares
    raise ValueError("Residuals are not finite in the initial point.")
ValueError: Residuals are not finite in the initial point.
```

**Comment by rzellem** [comment]
And here's the log file:
[exotic.log](https://github.com/rzellem/EXOTIC/files/5748493/exotic.log)

**Comment by rzellem** [comment]
Rob was able to run the dataset above just fine. Closing this issue now.
