### ISSUE TITLE
Filter for 0 prior to light curve fitting

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#485]
We filter for Nan's and infinites. The infinite would arise if the comp star is 0. We don't have a filter for zeros at the moment

**Comment by rzellem** [comment]
@pearsonkyle - getting new error:

```
Checking for variability in current comparison star... 
INFO: Query finished. [astroquery.utils.tap.core]
Traceback (most recent call last):
  File "exotic/exotic.py", line 3315, in <module>
    main()
  File "exotic/exotic.py", line 2689, in main
    nanmask = np.isnan(arrayFinalFlux) | np.isnan(arrayNormUnc) | np.isnan(arrayTimes) | np.isnan(arrayAirmass) | arrayFinalFlux > 0 | arrayNormUnc > 0
TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by tamimfatahi** [comment]
I recommend checking out the latest PR. Hopefully will solve this.

**Comment by tamimfatahi** [comment]
Completed in PR #488
