### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#509]
See Martin's PM to Rob on 1/27/21.

```
CAUTION: Measured flux amplitude is really low---are you sure there is a star at [315.49730934966664, 182.40895441455663]?
CAUTION: Measured flux amplitude is really low---are you sure there is a star at [312.8648840178346, 181.37763092578365]?
CAUTION: Measured flux amplitude is really low---are you sure there is a star at [312.8382974631824, 179.2083566320338]?


***************************************************************
Determining Optimal Aperture and Annulus Size for Comp Star #1
***************************************************************

Target X: 498.0 Target Y: 349.0

Comparison X: 489.0 Comparison Y: 406.0

array must not contain infs or NaNs
bounded  light curve fitting failed...check priors (e.g. estimated mid-transit time + orbital period)
bound: [0.0, 0.18607794065928396] prior: 8.365270995212024e-16
bound: [2459225.7092499, 2459225.7218529] prior: 2459225.7217790773
bound: [5.146515823418685, 5.541484176581315] prior: 5.541374300374194
bound: [1.4273792331328894, 10561.447459960982] prior: 1159.2490748727132
bound: [-1.0, 1.0] prior: -0.9999878876651229
removing bounds and trying again...
Traceback (most recent call last):
  File "exotic.py", line 3327, in <module>
    main()
  File "exotic.py", line 2757, in main
    myfit = lc_fitter(
  File "/mnt/c/Users/daneb/EXOTIC/exotic/api/elca.py", line 254, in __init__
    self.fit_LM()
  File "/mnt/c/Users/daneb/EXOTIC/exotic/api/elca.py", line 290, in fit_LM
    self.create_fit_variables()
  File "/mnt/c/Users/daneb/EXOTIC/exotic/api/elca.py", line 293, in create_fit_variables
    self.phase = getPhase(self.time, self.parameters['per'], self.parameters['tmid'])
  File "/mnt/c/Users/daneb/EXOTIC/exotic/api/elca.py", line 213, in getPhase
    return phase - int(np.nanmin(phase))
ValueError: cannot convert float NaN to integer
martin@DESKTOP-90ED50J:/mnt/c/Users/daneb/EXOTIC/exotic$
```

**Comment by rzellem** [comment]
I think this issue has already been resolved with release 0.33.0, so closing for now.
