### ISSUE TITLE
CoRoT-2 Data set problem

### ISSUE THREAD

**Issue by pearsonkyle** [rzellem/EXOTIC#596]
```

Martin Fowler  40 minutes ago
@Rob Zellem (he/him/his) Started to re-reduce my MObs data with EXOTIC v0.38.0 (Colab) to be compliant with AAVSO and encountered a failure of the photometry for the CoRoT-2 b transit of 20190920. This dataset was previously reduce with EXOTIC v0.7.1 and gave a very nice transit. It looks like v0.38.0 is having problems finding the stars during the photometry. Numerous WARNINGs and CAUTIONs warnings throughout the reduction, the last warning and caution, and the final error message are given below:
WARNING: trouble fitting Gaussian PSF to star at 135.18465953156507,223.14927677555664
  check location of comparison star in the first few images
  fitting parameters are out of bounds
  init: [-24.45675031   1.59175009  27.52051859  -0.85237249  54.81812872]
 lower: [130.18465953156507, 218.14927677555664, 0, 0, 0, -0.7853981633974483, -172.5]
 upper: [140.18465953156507, 228.14927677555664, 10000000.0, 20, 20, 0.7853981633974483, 375.5]
CAUTION: Measured flux amplitude is really low---are you sure there is a star at [139.07 223.63]?
IndexError, problem computing sky bg for -17777.7, -25406.6. Check if star is present or close to border.
Traceback (most recent call last):
  File "EXOTIC/exotic/exotic.py", line 1724, in skybg_phot
    cutoff = np.nanpercentile(data[yv, xv][mask], ptol)
IndexError: index -25413 is out of bounds for axis 0 with size 500
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "EXOTIC/exotic/exotic.py", line 3498, in <module>
    main()
  File "EXOTIC/exotic/exotic.py", line 2695, in main
    aper, annulus)
  File "EXOTIC/exotic/exotic.py", line 1706, in aperPhot
    bgflux, sigmabg, Nbg = skybg_phot(data, xc, yc, r + 2, dr)
  File "EXOTIC/exotic/exotic.py", line 1727, in skybg_phot
    cutoff = np.nanpercentile(data[yv, xv], ptol)
IndexError: index -25413 is out of bounds for axis 0 with size 500
Changed the comp stars so see if that solved the problem - but it didn't. Then tried to use the pre-reduced fluxes from the v0.7.1 reduction; got a nice transit plot similar to the original reduction but EXOTIC fell over with the following error:
****************************************
Fitting a Light Curve Model to Your Data
****************************************
25812it [05:10, 83.02it/s, batch: 8 | bound: 96 | nc: 1 | ncall: 89015 | eff(%): 28.997 | loglstar: -34.661 < -27.211 < -28.421 | logz: -45.612 +/-  0.244 | stop:  0.940]
Traceback (most recent call last):
  File "EXOTIC/exotic/exotic.py", line 3498, in <module>
    main()
  File "EXOTIC/exotic/exotic.py", line 3280, in main
    ax[0,0].plot(myfit.time, psf_data['target'][si,0][gi], 'k.')
UnboundLocalError: local variable 'psf_data' referenced before assignment
So looks like there are 2 problems:
(1) The photometry in v0.38.0 is not finding the stars which were previously found by v0.7.1.
(2) The UnboundLocalError.
Also noticed that the "Observation date" in the init.json file now has to be in the form dd-month-yyyy ... @Kalee Tock (she/her/hers) not sure whether your latest Colab notebook captures this change,
Link to the datset and inits.json file for you to play with if you want: https://www.dropbox.com/sh/46pj0te1zriuu0w/AADfNS-83z4g__OtpnaxpM4Ta?dl=0 (edited) 
FinalLightCurve_CoRoT-2 b_20-September-2019.png 
```

**Comment by pearsonkyle** [comment]
Data: https://www.dropbox.com/sh/46pj0te1zriuu0w/AADfNS-83z4g__OtpnaxpM4Ta?dl=0

**Comment by pearsonkyle** [comment]
https://github.com/rzellem/EXOTIC/pull/621
