### ISSUE TITLE
Qatar-1 Data set problem

### ISSUE THREAD

**Issue by pearsonkyle** [rzellem/EXOTIC#597]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/exotic/exotic.py", line 1573, in skybg_phot
    cutoff = np.nanpercentile(data[yv, xv][mask], ptol)
IndexError: index 500 is out of bounds for axis 0 with size 500
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/exotic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/exotic/exotic.py", line 2607, in main
    aper, annulus)
  File "/usr/local/lib/python3.7/dist-packages/exotic/exotic.py", line 1555, in aperPhot
    bgflux, sigmabg, Nbg = skybg_phot(data, xc, yc, r + 2, dr)
  File "/usr/local/lib/python3.7/dist-packages/exotic/exotic.py", line 1576, in skybg_phot
    cutoff = np.nanpercentile(data[yv, xv], ptol)
IndexError: index 500 is out of bounds for axis 0 with size 500
```

data: https://drive.google.com/drive/u/0/folders/1GwkB0rC-2pf9DX4O02Ip6A3ckjkG5Zdh

Probably something to do with centroiding and tracking

**Comment by pearsonkyle** [comment]
https://github.com/rzellem/EXOTIC/pull/621
