### ISSUE TITLE
Missing dependencies cause CLI install to fail

### ISSUE THREAD

**Issue by jpl-jengelke** [rzellem/EXOTIC#667]
```
      ERROR: Command errored out with exit status 1:
       command: /mnt/c/Users/richa/exotic_env/env/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-5tfm9782/astropy-helpers_6af99e7f74f947f7b92165e3cfcd0df5/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-5tfm9782/astropy-helpers_6af99e7f74f947f7b92165e3cfcd0df5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-gcy6w37w
           cwd: /tmp/pip-wheel-5tfm9782/astropy-helpers_6af99e7f74f947f7b92165e3cfcd0df5/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
```
also 
```
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xg_ntg2z/scikit-image_633ea812bf5548b68d78915e3dccdc44/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xg_ntg2z/scikit-image_633ea812bf5548b68d78915e3dccdc44/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ge7xre9z
         cwd: /tmp/pip-install-xg_ntg2z/scikit-image_633ea812bf5548b68d78915e3dccdc44/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xg_ntg2z/scikit-image_633ea812bf5548b68d78915e3dccdc44/setup.py", line 234, in <module>
        'build_ext': openmp_build_ext(),
      File "/tmp/pip-install-xg_ntg2z/scikit-image_633ea812bf5548b68d78915e3dccdc44/setup.py", line 58, in openmp_build_ext
        from numpy.distutils.command.build_ext import build_ext
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/54/fd/c1b0bb8f6f12ef9b4ee8d7674dac82cd482886f8b5cd165631efa533e237/scikit-image-0.17.2.tar.gz#sha256=bd954c0588f0f7e81d9763dc95e06950e68247d540476e06cb77bcbcd8c2d8b3 (from https://pypi.org/simple/scikit-image/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by jpl-jengelke** [comment]
There is also strange behavior with the latest `pip` which I need to look into.

**Comment by jpl-jengelke** [comment]
This should be resolved with earlier rework of `setup.py` and the latest updates of `pip`. Closing this for now, and if errors arise again, it can be reopened for further troubleshooting.
