### ISSUE TITLE
Fix Realtime Reduction

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#670]
Need to make instructions more clear about the purpose of the real time reductions

also, need to fix the error:

```
Enter the Planet Name. Make sure it matches the case sensitive name and spacing used on Exoplanet Archive (https://exoplanetarchive.ipac.caltech.edu/index.html): HAT-P-32 b

Enter the directory path where imaging files are located. (Example using the sample data: sample-data/HatP32Dec202017): sample-data/HatP32Dec202017
Traceback (most recent call last):
  File "exotic/exotic.py", line 2762, in <module>
    main()
  File "exotic/exotic.py", line 1681, in main
    exotic_infoDict = inputs_obj.real_time()
  File "/Users/rzellem/Documents/EXOTIC/exotic/inputs.py", line 83, in real_time
    self.info_dict[key] = self.params[key](self.info_dict[key])
TypeError: target_star_coords() missing 1 required positional argument: 'planet'

```

**Comment by rzellem** [comment]
@rzellem fixed the planet name error above, but now we need to fix the alignment section

calling in @pearsonkyle to help with fixing the alignment

**Comment by tamimfatahi** [comment]
Completed in PR #828
