### ISSUE TITLE
AstroPy error: Additional install step on some Python installations

### ISSUE THREAD

**Issue by jpl-jengelke** [rzellem/EXOTIC#714]
Python no longer installs certificates by default. If the machine is older then a script must be run to update the certificates. Not doing this means EXOTIC fails to launch. 

```
FP-MXS02:EXOTIC jengelke$ exotic
Created TAP+ (v20200428.1) - Connection:
	Host: gea.esac.esa.int
	Use HTTPS: True
	Port: 443
	SSL Port: 443
Created TAP+ (v20200428.1) - Connection:
	Host: gea.esac.esa.int
	Use HTTPS: True
	Port: 443
	SSL Port: 443
WARNING: AstropyDeprecationWarning: The private astropy._erfa module has been made into its own package, pyerfa, which is a dependency of astropy and can be imported directly using "import erfa" [astropy._erfa]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1422, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/exotic", line 5, in <module>
    from exotic.exotic import main
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/exotic/exotic.py", line 108, in <module>
    from barycorrpy import utc_tdb
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/barycorrpy/__init__.py", line 1, in <module>
    from .utc_tdb import *
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/barycorrpy/utc_tdb.py", line 19, in <module>
    from . import PINT_erfautils as PINT
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/barycorrpy/PINT_erfautils.py", line 20, in <module>
    iers_b_file = download_file(IERS_B_URL, cache=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/astropy/utils/data.py", line 1257, in download_file
    raise errors[sources[0]]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/astropy/utils/data.py", line 1222, in download_file
    f_name = _download_file_from_source(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/astropy/utils/data.py", line 1051, in _download_file_from_source
    with urlopener.open(req, timeout=timeout) as remote:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)>
FP-MXS02:EXOTIC jengelke$ 
```

**Comment by jpl-jengelke** [comment]
The script `Install Certificates` should be executed.  (Documented at https://github.com/python/cpython/blob/f171877ebe276749f31386baed5841ce37cbee2e/Mac/BuildScript/resources/ReadMe.rtf#L19 )

On Macs this is at 
```
/Applications/Python\ 3.9/Install\ Certificates.command
```

It's not clear is it's required on PCs but this would be an extra step on an automated installer.

**Comment by jpl-jengelke** [comment]
This can be closed. It was posted here for documentation purposes.
